#SPDX-License-Identifier: MIT-0
---
# tasks file for rocketmq

- name: 清除旧容器
  shell: 'docker-compose -f {{ OPT_PATH }}/rocketmq/docker-compose.yaml rm -fsva;rm -rf {{ OPT_PATH }}/rocketmq'
  ignore_errors: yes

- name: 创建部署目录
  shell: '[[ ! -d "{{ OPT_PATH }}/rocketmq" ]] && mkdir -vp {{ OPT_PATH }}/rocketmq'
  ignore_errors: yes

- name: 配置 broker.conf
  template: src=broker.conf.j2 dest={{ OPT_PATH }}/rocketmq/broker.conf

- name: 配置 docker-compose.yaml
  template: src=docker-compose.yaml.j2 dest={{ OPT_PATH }}/rocketmq/docker-compose.yaml

- name: 运行服务
  shell: 'docker-compose -f {{ OPT_PATH }}/rocketmq/docker-compose.yaml up -d'